### ISSUE TITLE
Obtain Logical Org Structure

### ISSUE THREAD

**Issue by CIS-rdbrown** [private-pilot/fitness-model#10]
work with coaches on proper org layout.

TOP ORG (CIS)
Sub org (OIT/OTC)
Division
Branch
Portfolio
Team/Application

**Comment by CIS-rdbrown** [comment]
LINK https://github.com/private-pilot/fitness-model/issues/9

**Comment by CIS-gvoit** [comment]
https://github.com/private-pilot/fitness-model/blob/master/db/schemas/schemav4.pdf
