### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by CIS-rdbrown** [private-pilot/fitness-model#12]
Gents lets get some Milestones w/ dates ie  break into 2 week sprints - we can have a user story session on Monday (5/16) in ATOWN?

**Comment by CIS-gvoit** [comment]
Sounds good to me!

**Comment by CIS-gvoit** [comment]
We will operate on a 1 week cadence with weekly meetups on Tuesday in McLean and regular checkins on USCIS Slack.
