### ISSUE TITLE
Workflow for Creating a New "Result"

### ISSUE THREAD

**Issue by CIS-gvoit** [private-pilot/fitness-model#19]
A team lead should be able to create a "New Assessment". When this happens, all questions & answers for the associated assessment should be tied together with a response with the "0" value for that question (e.g. If it is a "Yes, No, Planning to", the value would be defaulted to "No").

**Comment by CIS-gvoit** [comment]
Values at current are "Yes, No, Select". No entry is created in the "responses" table until a user enters a value (chooses an option from the dropdown) for the input.

Because the action generated by onSelect is an HTTP PUT request, we need to add functionality to the express API to check whether an entry already exists. If it does not exist, we should INSERT into, instead of issuing an UPDATE command.

**Comment by CIS-gvoit** [comment]
Additional blocker noted here... in order to render the dropdown in Category --> QuestionList --> QuestionListItem, it relies on an API call to /fitness_card which joins responses (and assumes that there is a default response for every question defaulted to "Select" for that "result" [recall that a "result" is a single instance of an "assessment" and an "assessment" is the current "version"]).

The above comment will not work at current due to the fact that the API endpoint /fitness_card/:id relies on responses, and none would be generated until a user chose an option for each question in the dropdown.

**Comment by hassanriaz** [comment]
The create new result button will post the userid and assessment id to /results to create the new result and its corresponding default responses.

I know you're still working on the whole login portion -- so we'll figure out later how to retrieve the currently logged in user's id after you have that hashed out -- but what about the current result id?

The get_fitness_card query currently seems to assume there is only result, so the moment I add another and its set of responses, the query returns more than what we expect.  I will have to alter this query to add a parameter for the currently selected "result"....

Which brings me to my next question -- how are we selecting from the list of results for a particular assessment?  

I feel like we may need to alter the route structure to something like `/result/2/category/1` or something?

That way `/result` could be a container where the result is selected, leading to `result/1/category/1` where category 1's questions for result 1 are shown for the "current" user.

And also, how do assessments play into this?  Will a user be able to have multiple assessments?  If that's the case, we may need a `/assessment/#` in front of what I have...

**Comment by CIS-gvoit** [comment]
You're totally right - at current, if there were more than 1 result (i.e. more than one response for each question), it would return all of the information on that category. I agree that we need to change it to something like you posted above: ```/result/2/category/1```.

I also agree that ```/assessment/:assessment_id/result/:result_id/category/:category_id``` should be the "full" call for fetching a "fitness-card" (instead of the current implementation of ```/fitness_card/:id```).

**Comment by CIS-gvoit** [comment]
After looking further into this - I am not convinced we need ```/assessments/:id``` to be part of that, since result_id is unique.

We don't have assessment1 with results 1, 2, 3, 4, 5, 6 and assessment 2 with results 1, 2, 3, 4, 5, 6).

Instead we would have assessment 1 with results 1, 2, 3, 4, 5, 6 and assessment 2 with results 7, 8, 9, 10, 11, 12, etc.

I think the route for ```fitness_card:/category_id``` (with the current table names) should change to ```result/:result_id/category/:category_id```... But I also think we should rename the "results" table to something else... because it isn't really a "result", it's really just an instance of an assessment. So perhaps we should rename the "assessments" table to "versions" and the "results" table to "assessments". This would then make the query ```version/:version_id/assessments/:assessment_id/category/:category_id```.

Let me know what you think about that.

**Comment by CIS-gvoit** [comment]
DB has been updated
assessments in schemav4 is versions in schemav5
results in schemav4 is assessments in schemav5
commented agency hierarchy to create focused schema diagram (agency hierarchy is useful for a later version of the app)

[See schemav5](https://github.com/private-pilot/fitness-model/blob/master/db/schemas/schemav5.pdf)

**Comment by hassanriaz** [comment]
Ok so here is my way forward:

* Merge your latest changes to master to my branch and make sure the response initialization still works
* Rework the routing for frontend to be `/assessments/:assessment_id/category/:category_id
* Add a container at `/assessments/` where you select from existing assessments -- is there a wireframe from this or should i just improvise?

I may have some time today to work on this.

**Comment by CIS-gvoit** [comment]
@hassanriaz's commit history above completes this feature.
