### ISSUE TITLE
Miscellaneous Fixes for Assessments List page and Questions Page

### ISSUE THREAD

**Issue by hassanriaz** [private-pilot/fitness-model#69]
- [x] Populate start time on creation
- [x] Submit Assessment button on level 3 adds end time
- [x] Assessments Page shows results if completed, otherwise takes you to category 1
- [x] Some sort of notification that Question is being saved in QuestionListItem
- [x] Cannot create new if an existing one is not complete
- [x] Checkbox for Sidebar if questions are complete (ie not Select)

**Comment by CIS-gvoit** [comment]
@hassanriaz I have some skeleton code for this in CategoryActions.js

```
/* Not live yet
 * updateChecked takes category_id (int) and checked (boolean)
 * Used to track whether a category-item in SideBar should be checked or empty.
 * If true, checked, else empty.
 */
// export function updateChecked(category_id, checked) {
// 	return {
// 		type: UPDATE_CHECKED,
// 		payload: { checked }
// 	};
// }
```

**Comment by hassanriaz** [comment]
Oh man I didn't even see your comment here about an action.  

I just checked myself whether or not the category is complete, seemed simple enough to examine questions/answers since they're already in redux.
