### ISSUE TITLE
"Categories" Redux State Applied to "Category" Container

### ISSUE THREAD

**Issue by CIS-gvoit** [private-pilot/fitness-model#77]
We now have all necessary data for displaying our "Self-Assessment" screens as well as the data required for our "Results" screen.

We must now have the concept of a "Selected" category.
This should be by index in the array of categories (i.e. will be categories[i].category_id)
The Next & Prev buttons point to +/- 1 of the current index.

- [x] STEP 1: Sidebar
- For now, categories_list.js can just continue to call fetchCategories.
- May want to eventually change this to pull from Redux state (since the information is there... just not the easiest to grab).

- [x] STEP 2: Category.js
- Makes call to newFetchCategory (based on assessment_id) instead of fetchCategory
- Then populates itself with one category's worth of the data it just fetched after checking ```categories.selected```
- mapStateToProps should include ```categories.categories```

- [x] STEP N: Flip the button to point to the newFetchCategories action
- Almost want 2 actions to occur here...
- Updates ```categories.selected``` and ```assessments.selected```

**Comment by hassanriaz** [comment]
At this point, the next/prev buttons shouldnt link to anything, just have them change the state of category.selected and everything should react.

* Agree with Step 1, if we have the data in state, no need to fetchCategories.
* Step 2 -- Basically you're just saying to connect the category container to the new redux state that is hydrated by newFetchCategory?  Just make sure it sets up QuestionsList/ListItem same way it does now and everything should work as expected.
* Step N -- Which button?  Where you select an assessment?  Yea, should basically just set those 2 redux variables.

**Comment by CIS-gvoit** [comment]
Started working on Step N (in response to your question, the "button" I'm referring to is clicking either a "completed" Assessment or an "in-progress" Assessment).

redux-promise falls short on dispatching multiple actions (which is necessary, since we have to update ```assessments.selected``` and ```categories.selected``` before the Link executes.

I think my next step is to add redux-thunk to the project and to begin reworking each function one at a time (will just work on modifying the addAssessment function to use redux-thunk instead of redux-promise).

**Comment by CIS-gvoit** [comment]
Apparently redux-thunk requires a newer version of redux than we have installed... and trying to resolve the 5-6 other dependencies on all these npm modules proved quite intricate. Going to nuke my branch and resume next week...

**Comment by CIS-gvoit** [comment]
Resolved 2 of 3 steps with 95d84cf78b815248a727726da222c9d2734729a1

**Comment by CIS-gvoit** [comment]
Sidebar working. fb0c4cf29a44e7e4fca555ce221509146624cea2
