### ISSUE TITLE
Modify Schema to Account for Organization Structure

### ISSUE THREAD

**Issue by CIS-gvoit** [private-pilot/fitness-model#8]
We need to account for a user belonging to different "teams".

Initial idea looks something like...
- CIS Organization
  - Division
    - Portfolio
      - Application
    - Branch
      - Team

We need to think through the types of users we could have and what different reports they would like to be able to see. Eventually, we will also want result aggregation which combines the results of multiple fitness reports to pinpoint weaknesses / strengths across a larger group of teams (e.g. across a Division, our weakest DevOps practice is our "Release Management").

**Comment by rdpa** [comment]
Updated schema
https://github.com/private-pilot/fitness-model/commit/0a28fd8fbd53ba0a14c516da3559d5d7447f78c1

**Comment by rdpa** [comment]
Added updated schema diagram
https://github.com/private-pilot/fitness-model/commit/ce6cfbc1394f64c69d23664d44416e451ec2834a

**Comment by rdpa** [comment]
https://github.com/private-pilot/fitness-model/commit/95d91e809d853bb461a7ee881348234b9cb26adb

**Comment by reedflinch** [comment]
@rdpa if you reference #8 in your commit messages you won't have to manually comment. may make your life slightly easier.

**Comment by CIS-gvoit** [comment]
Discussion with David Blair from ELIS has given us something like the following structure:

Mark
 - ITPM
   - Product Owner
   - Release Manager
     - Product Manager
       - Team

**Comment by CIS-gvoit** [comment]
Latest version here: https://github.com/private-pilot/fitness-model/blob/master/db/schemas/schemav4.pdf
